# Generated by Django 4.2.3 on 2023-07-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_username',
            field=models.CharField(max_length=150, unique=True, verbose_name='никнейм в телеграме'),
        ),
    ]
