version: '3.7'

services:
  db_habit:
    restart: always
    image: postgres:14-alpine
    user: ${POSTGRES_USER}
    container_name: db_habit
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  redis_habit:
    image: redis:7.0.2-alpine
    container_name: redis_habit
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5

  app_habit:
    build: .
    container_name: app_habit
    depends_on:
      db_habit:
        condition: service_healthy
      redis_habit:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - ./static:/app/static
    command: >
      bash -c "python manage.py collectstatic --no-input
      && python manage.py migrate
      && python manage.py fill
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  celery_habit:
    restart: always
    build: .
    container_name: celery_habit
    command: >
      bash -c "celery -A config worker --beat --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - app_habit
      - redis_habit

  nginx_habit:
    build: ./nginx
    container_name: nginx_habit
    depends_on:
      - app_habit
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static

  telegrambot_habit:
    container_name: telegrambot_habit
    build: .
    command: python habit_tracker/bot.py
    volumes:
      - .:/app
    depends_on:
      - db_habit
      - redis_habit
      - app_habit


volumes:
  pg_data:
  static:


