# Generated by Django 4.2.3 on 2023-07-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveIntegerField(default=120, verbose_name='длительность выполнений в секундах'),
        ),
    ]
