# Generated by Django 4.2.3 on 2023-07-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_habit_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodhabit',
            options={'ordering': ('time',), 'verbose_name': 'полезная привычка', 'verbose_name_plural': 'полезные привычки'},
        ),
    ]
