# Generated by Django 4.2.3 on 2023-08-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_alter_goodhabit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pleasanthabit',
            options={'ordering': ('time',), 'verbose_name': 'приятная привычка', 'verbose_name_plural': 'приятные привычки'},
        ),
    ]
